# Generated by Django 5.0.6 on 2024-05-15 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminRestaurante', '0003_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminRestaurante.cliente')),
                ('Empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminRestaurante.empleado')),
                ('Mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminRestaurante.mesa')),
            ],
        ),
    ]
