# Generated by Django 5.0.6 on 2024-05-15 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminRestaurante', '0004_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(max_length=50)),
                ('disponibilidad', models.BooleanField()),
                ('Pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminRestaurante.pedido')),
            ],
        ),
    ]
